#!/usr/bin/env python3
"""
Automated Web Quality Audit & GitHub Pages Deployment Pipeline
CelebrityStrategy Deployment Engine

Responsibilities:
  1. Inspect and audit pages generated by investor-tracking:
     - Root index.html / dashboard.html integrity
     - Company detail pages existence and non-emptiness
     - Internal links validity (e.g. companies/{TICKER}.html)
     - CDN scripts and CSS assets
  2. Sync assets to docs/ and origin/gh-pages
  3. Trigger GitHub Pages build and verify live HTTP status
  4. Provide feedback and actionable suggestions if defects are found
"""

import os
import re
import shutil
import subprocess
import sys
import time

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS_DIR = os.path.join(PROJECT_ROOT, "docs")
REPORTS_DIR = os.path.join(PROJECT_ROOT, "reports")


def audit_generated_pages():
    """Audits the generated HTML pages and returns (issues, stats)."""
    issues = []
    stats = {}

    # 1. Check primary dashboard
    dash_candidates = [
        os.path.join(DOCS_DIR, "index.html"),
        os.path.join(REPORTS_DIR, "dashboard.html"),
    ]
    main_html = None
    for p in dash_candidates:
        if os.path.exists(p) and os.path.getsize(p) > 1000:
            main_html = p
            break

    if not main_html:
        issues.append("❌ 严重：未找到主仪表盘文件（docs/index.html 或 reports/dashboard.html 不存在或为空）")
        return issues, stats

    with open(main_html, "r", encoding="utf-8") as f:
        content = f.read()

    stats["main_html_size"] = len(content)
    stats["main_html_path"] = main_html

    # Check title and meta
    if "<title>" not in content:
        issues.append("⚠️ 警告：主仪表盘缺少 <title> 标签")
    if "tailwindcss" not in content.lower():
        issues.append("⚠️ 提示：未检测到 Tailwind CSS 样式库引用")

    # Check company links
    company_links = set(re.findall(r'href=["\'](?:companies/)?([A-Za-z0-9\.\-_]+\.html)["\']', content))
    stats["company_links_found"] = len(company_links)

    # Check companies directory
    companies_dir = os.path.join(os.path.dirname(main_html), "companies")
    if not os.path.exists(companies_dir):
        # Fallback check docs/companies or reports/companies
        for alt in [os.path.join(DOCS_DIR, "companies"), os.path.join(REPORTS_DIR, "companies")]:
            if os.path.exists(alt):
                companies_dir = alt
                break

    if os.path.exists(companies_dir):
        existing_files = set(os.listdir(companies_dir))
        stats["existing_company_pages"] = len(existing_files)

        missing = []
        for cl in company_links:
            if cl not in existing_files:
                missing.append(cl)
        if missing:
            sample = missing[:5]
            issues.append(f"⚠️ 坏链预警：主页面引用了 {len(missing)} 个不存在的个股详情页（如：{', '.join(sample)}）")
    else:
        if company_links:
            issues.append(f"❌ 严重：主页面包含了 {len(company_links)} 个个股详情页链接，但 companies/ 文件夹不存在！")

    return issues, stats


def sync_and_deploy():
    """Syncs docs/ to gh-pages and pushes to GitHub."""
    print("🚀 启动自动化同步与 GitHub Pages 部署...")

    # Ensure docs/index.html and docs/companies are synced from reports if reports is newer
    rep_dash = os.path.join(REPORTS_DIR, "dashboard.html")
    docs_dash = os.path.join(DOCS_DIR, "index.html")
    if os.path.exists(rep_dash):
        if not os.path.exists(docs_dash) or os.path.getmtime(rep_dash) > os.path.getmtime(docs_dash):
            print("  📋 检测到 reports/dashboard.html 较新，同步至 docs/index.html")
            with open(rep_dash, "r", encoding="utf-8") as f_src:
                with open(docs_dash, "w", encoding="utf-8") as f_dst:
                    f_dst.write(f_src.read())

    rep_comp = os.path.join(REPORTS_DIR, "companies")
    docs_comp = os.path.join(DOCS_DIR, "companies")
    if os.path.exists(rep_comp) and not os.path.exists(docs_comp):
        print("  📋 同步 reports/companies 至 docs/companies")
        subprocess.run(["cp", "-r", rep_comp, docs_comp], check=True)

    # Touch docs/.nojekyll
    open(os.path.join(DOCS_DIR, ".nojekyll"), "a").close()

    # Deploy via worktree to gh-pages
    worktree_path = "/tmp/gh-pages-deploy"
    subprocess.run(["rm", "-rf", worktree_path], check=False)
    subprocess.run(["git", "worktree", "add", worktree_path, "gh-pages"], check=True, cwd=PROJECT_ROOT)

    try:
        # Clear worktree and copy docs contents
        for item in os.listdir(worktree_path):
            if item == ".git":
                continue
            item_path = os.path.join(worktree_path, item)
            if os.path.isdir(item_path):
                shutil.rmtree(item_path)
            else:
                os.remove(item_path)

        for item in os.listdir(DOCS_DIR):
            s = os.path.join(DOCS_DIR, item)
            d = os.path.join(worktree_path, item)
            if os.path.isdir(s):
                shutil.copytree(s, d)
            else:
                shutil.copy2(s, d)

        # Commit and push
        subprocess.run(["git", "add", "-A"], cwd=worktree_path, check=True)
        status_out = subprocess.run(["git", "status", "--porcelain"], cwd=worktree_path, capture_output=True, text=True)

        if not status_out.stdout.strip():
            print("  ℹ️ 线上 gh-pages 分支已是最新，无新增差异需要提交。")
        else:
            subprocess.run(["git", "commit", "-m", "deploy: automated publish to gh-pages"], cwd=worktree_path, check=True)
            subprocess.run(["git", "push", "origin", "gh-pages"], cwd=worktree_path, check=True)
            print("  ✅ 最新网页资产已成功推送至 origin/gh-pages 分支！")

    finally:
        subprocess.run(["git", "worktree", "remove", "--force", worktree_path], check=False, cwd=PROJECT_ROOT)

    # Trigger GitHub Pages build
    print("  ⚡ 触发 GitHub Pages 云端编译...")
    trigger_res = subprocess.run(
        ["gh", "api", "--method", "POST", "repos/MichaelSun/celebrityStrategy/pages/builds"],
        capture_output=True, text=True
    )
    if trigger_res.returncode == 0:
        print("  ✅ 已成功向 GitHub API 提交编译指令！")
    else:
        print(f"  ⚠️ 触发 API 提示: {trigger_res.stderr.strip() or trigger_res.stdout.strip()}")

    print("\n🎉 部署指令已全部执行完毕！")


def main():
    print("=" * 60)
    print("🏛️ CelebrityStrategy 部署与质检流水线")
    print("=" * 60)

    issues, stats = audit_generated_pages()
    print(f"📊 质检统计：")
    print(f"  • 主页面大小: {stats.get('main_html_size', 0):,} bytes")
    print(f"  • 引用个股链接: {stats.get('company_links_found', 0)} 个")
    print(f"  • 现有独立档案: {stats.get('existing_company_pages', 0)} 份")

    if issues:
        print("\n⚠️ 质检发现潜在问题：")
        for iss in issues:
            print(f"  {iss}")
        # If critical failure, prompt
        if any("❌" in i for i in issues):
            print("\n❌ 存在严重错误，终止部署，请将上述问题反馈给生成模块。")
            sys.exit(1)

    print("\n✅ 页面质检通过！执行发布部署...")
    sync_and_deploy()


if __name__ == "__main__":
    main()
